### ISSUE TITLE
[Question] How to get column lineage from spark with proxy?

### ISSUE THREAD

**Issue by sdkdgrant** [OpenLineage/OpenLineage#1054]
I'm just getting started trying to capture lineage data from pyspark on my local computer. I've followed the instructions in the [proxy readme](https://github.com/OpenLineage/OpenLineage/blob/main/proxy/README.md), using `proxy.example.yml` logging type changed from `console` to `file` according to [dropwizard documentation link](https://www.dropwizard.io/en/stable/manual/configuration.html#logging) in the file.

From `proxy.yml`:
```yml
logging:
  # Levels: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, ALL, OFF
  level: ${LOG_LEVEL:-INFO}
  appenders:
  - type: file
    currentLogFilename: /home/sdkdgrant/sandbox/openlineage.log
    archivedLogFilenamePattern: /home/sdkdgrant/sandbox/openlineage-%d.log.gz
    archivedFileCount: 5
```
This is the code I'm using to create the spark session:
```python
spark = (
    SparkSession.builder
    .config("spark.jars.packages", "io.openlineage:openlineage-spark:0.13.1")
    .config("spark.extraListeners", "io.openlineage.spark.agent.OpenLineageSparkListener")
    .config('spark.openlineage.host', 'http://localhost:8080')
    .config('spark.openlineage.namespace', 'spark_local')
    .getOrCreate()
)
```
This is the simple code to track the lineage of:
```python
spark.range(10) \
  .write.mode("overwrite").parquet("df")

spark.read.parquet("df") \
  .withColumn("col1", f.col("id")*2) \
  .write.mode("overwrite").parquet("df2")
```
What steps do I need to take to start tracking column lineage?
Thanks.
