### ISSUE TITLE
[PROPOSAL] Add support for `debug` or `verbose` mode in clients

### ISSUE THREAD

**Issue by wslulciuc** [OpenLineage/OpenLineage#1196]
## Problem

OpenLineage integrations emit [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.yml) specific [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets), but also  _developer_ specific facets that fall into the following categories:

* `debug`: used for improving our [integrations](https://github.com/OpenLineage/OpenLineage/tree/main/integration) (ex: the [`spark_unknown`](https://github.com/OpenLineage/OpenLineage/blob/main/integration/spark/shared/facets/spark/v1/unknown-entry-facet.json) facet is used to capture spark plan metadata for nodes not yet supported)
* `verbose`: used for diagnostic information (ex: the `spark.logicalPlan` facet is used to analyze the logical plan of your spark job)

_Developer_ specific facets are useful, but, as we've see in production, such facets can be very large, change infrequently from run-to-run,  and cause degradations in performance for the system where the integrations is configured. For example, complex spark logical plans can exceed **`1MB`** in size; the `spark.logicalPlan` facet is captured along with every request resulting in storage costs but also increased network overhead. **In this proposal, we outline the introduction and usage of two modes: `debug` and `verbose`. We also discuss expanding the `openlineage.yml` to support these modes.**

## Add `debugMode` and `verboseMode` to `openlineage.yml`

OpenLineage clients are configured using `openlineage.yml` (see [Configuration](https://github.com/OpenLineage/OpenLineage/tree/main/client/java#configuration) section for `openlineage-java`). Within the configuration file, users can define the [`transport`](https://github.com/OpenLineage/OpenLineage/tree/main/client/java#transports) used to emit OL events (ex: [`Httptransport`](https://github.com/OpenLineage/OpenLineage/tree/main/client/java#httptransport)). Below, we extend `openlineage.yml` to support the configuration of `debugMode` and `verboseMode`:

```yaml
debugMode:
  enabled: <bool> # Enables debug facets to be emitted along with OL events (ex: 'spark_unknown')
  facets: [array] # Provides a way to specify one or more debug facet to captured (default: 'All')
verboseMode:
  enabled: <bool> # Enables diagnostic information to be emitted along with OL events (ex: 'spark.logicalPlan')
  facets: [array] # Provides a way to specify one or more verbose facet to captured (default: 'All')
transport:
  type: <type>
  # ... transport specific configuration
```

## Example usage of `debugMode` and `verboseMode` in `ol-spark`

```yaml
# Enable 'debugMode' with specific facets to capture
debugMode:
  enabled: true
  facets: ['spark_unknown'] # Only capture the 'spark_unknown' facet
# Enable 'verboseMode' with facets not defined (defaults to 'All')
verboseMode:
  enabled: true
  # When 'facets' is not provided, all facets are captured by the integration
transport:
  type: HTTP
  url: http://localhost:5000
  auth:
    type: api_key
    api_key: f38d2189-c603-4b46-bdea-e573a3b5a7d5
```

Then, in **class** [`InternalEventHandlerFactory `](https://github.com/OpenLineage/OpenLineage/blob/main/integration/spark/app/src/main/java/io/openlineage/spark/agent/lifecycle/InternalEventHandlerFactory.java) we can define **class**  `OpenLineageOptions` in our clients to determine which facets are enabled (reference the below only code as an example usage, my not compile 😅):

```java
  @Override
  public Collection<CustomFacetBuilder<?, ? extends RunFacet>> createRunFacetBuilders(
      OpenLineageContext context) {
    Builder<CustomFacetBuilder<?, ? extends RunFacet>> listBuilder;
    listBuilder =
        ImmutableList.<CustomFacetBuilder<?, ? extends RunFacet>>builder()
            .addAll(
                generate(
                    eventHandlerFactories, factory -> factory.createRunFacetBuilders((context))))
            .add(OpenLineageOptions.debugMode().facets(),
                 OpenLineageOptions.verboseMode().facets(),
                 new SparkVersionFacetBuilder(context));
    if (DatabricksEnvironmentFacetBuilder.isDatabricksRuntime()) {
      listBuilder.add(new DatabricksEnvironmentFacetBuilder());
    }
    return listBuilder.build();
  }
```
