### ISSUE TITLE
[PROPOSAL] Add circuit breaker to `java` client

### ISSUE THREAD

**Issue by wslulciuc** [OpenLineage/OpenLineage#1255]
## Problem

In the wild, we've seen users of `openlineage-spark` request support to kill / pause metadata collection if resource usage (i.e. JVM) exceeds some threshold `T`. For example:

* MEM threshold > `20%`
* Garbage collection CPU threshold > `10%`

Adding a circuit breaker to our `java` client would prevent the OL integration from exhausting resources on the system it’s deployed (at scale, we've seen performance degradation of production spark clusters 😭). **In other words, low free memory and high cpu time on garbage collecting would trip the “Circuit Breaker”** (see [Circuit breaker for Java custom instrumentation](https://docs.newrelic.com/docs/apm/agents/java-agent/custom-instrumentation/circuit-breaker-java-custom-instrumentation/)  from New Relic that can inspire our solution). 

## Add `circuitBreaker` to `openlineage.yml`

```yaml
circuitBreaker:
  enabled: <bool>        # Enables the circuit breaker
  memoryThreshold: <int> # MEM threshold percentage as INT
  gcCpuThreshold: <int>  # Garbage collection CPU threshold percentage as INT
transport:
  type: <type>
  # ... transport specific configuration
```

We don't have to author our own circuit breaker, and can leverage the [`resilience4j`](https://resilience4j.readme.io/docs/circuitbreaker) lib. to create a [`CircuitBreakerRegistry`](https://resilience4j.readme.io/docs/examples).

## Example usage of `circuitBreaker`

```yaml
# Enable 'circuitBreaker' with specific memory threshold only
circuitBreaker:
  enabled: true
  memoryThreshold: 20 # Trip 'circuitBreaker' when MEM threshold > 20
transport:
  type: HTTP
  url: http://localhost:5000
  auth:
    type: api_key
    api_key: f38d2189-c603-4b46-bdea-e573a3b5a7d5
```

When the circuit breaker is "tripped", the integration would suspend metadata collection. An open question would be, do we want metadata collection to resume when the memory threshold < `20`?

**Comment by mobuchowski** [comment]
>(at scale, we've seen performance degradation of production spark clusters 😭)

@wslulciuc are you saying that emitting events is heavy, serialization, or just collection?

**Comment by wslulciuc** [comment]
> ... are you saying that emitting events is heavy, serialization, or just collection?

Yeah, great clarification question @mobuchowski. The performance degradation (at least in the scenario I've seen) is serialization.

**Comment by howardyoo** [comment]
> > ... are you saying that emitting events is heavy, serialization, or just collection?
> 
> Yeah, great clarification question @mobuchowski. The performance degradation (at least in the scenario I've seen) is serialization.

When the circuit breaker happens, what are the outcome of that? I would like the OL even to still emit, but with error facet stating the extraction was halted due to the resource constraint that fired the circuit breaker. We currently do not have means to show the error facet, but it is being planned.

**Comment by mobuchowski** [comment]
I think with https://github.com/OpenLineage/OpenLineage/issues/2375 we want to have generic interface that would enable multiple use cases: both CPU, memory or even some custom mechanism.
```
circuitBreaker:
  type <string>          # Defines the class of Circuit Breaker that's enabled - Service Loader driven https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html
  minimumMemoryAvailable: <int> # Example conf: free memory threshold percentage as INT
  timeout: <int>  # Example conf: limit OL processing to this amount in seconds
transport:
  type: <type>
  # ... transport specific configuration
```

The same would be configurable via Spark config. 
```
spark.openlineage.circuitbreaker.type - io.openlineage.circuitbreaker.SimpleCircuitBreaker
spark.openlineage.circuitbreaker.minimumMemoryAvailable - 20
spark.openlineage.circuitbreaker.timeout - 30
```

From my side, we'd like to see simple implementation that does a "filter" check on a start of a job: emit OL event only if there's some % of a free memory in the system on a event start. If not, then just log the fact. The CPU timeout circuit breaker could be contained in the same implementation.

Other circuit breakers could define their own config in `spark.openlineage.circuitbreaker` namespace.
