### ISSUE TITLE
[SPARK] The integration fails to produce inputs and outputs in a Kafka-to-Kafka scenario

### ISSUE THREAD

**Issue by d-m-h** [OpenLineage/OpenLineage#2137]
# Problem Statement

As the title suggests, when a Spark job is running in a streaming configuration that performs a Kafka-to-Kafka data flow, the integration fails to emit any events with inputs and/or outputs.

Here's an example of an output that the connector emits:

```
23/09/27 18:17:22 DEBUG OpenLineageRunEventBuilder: Visiting query plan Optional[== Parsed Logical Plan ==
WriteToMicroBatchDataSource org.apache.spark.sql.kafka010.KafkaSourceProvider$KafkaTable@2e679177, c3df858a-d481-456f-9665-3ff0c2d6d19a, [kafka.bootstrap.servers=localhost:9092,localhost:9093,localhost:9094, topic=target, checkpointLocation=/Users/dhawes/Projects/spark-streaming-openlineage], Append, 0
+- StreamingDataSourceV2Relation [key#7, value#8, topic#9, partition#10, offset#11L, timestamp#12, timestampType#13], org.apache.spark.sql.kafka010.KafkaSourceProvider$KafkaScan@2095a606, KafkaV2[Subscribe[source]], {"source":{"0":11}}, {"source":{"0":11}}

== Analyzed Logical Plan ==
WriteToMicroBatchDataSource org.apache.spark.sql.kafka010.KafkaSourceProvider$KafkaTable@2e679177, c3df858a-d481-456f-9665-3ff0c2d6d19a, [kafka.bootstrap.servers=localhost:9092,localhost:9093,localhost:9094, topic=target, checkpointLocation=/Users/dhawes/Projects/spark-streaming-openlineage], Append, 0
+- StreamingDataSourceV2Relation [key#7, value#8, topic#9, partition#10, offset#11L, timestamp#12, timestampType#13], org.apache.spark.sql.kafka010.KafkaSourceProvider$KafkaScan@2095a606, KafkaV2[Subscribe[source]], {"source":{"0":11}}, {"source":{"0":11}}

== Optimized Logical Plan ==
WriteToDataSourceV2 org.apache.spark.sql.execution.streaming.sources.MicroBatchWrite@6b69d31b
+- StreamingDataSourceV2Relation [key#7, value#8, topic#9, partition#10, offset#11L, timestamp#12, timestampType#13], org.apache.spark.sql.kafka010.KafkaSourceProvider$KafkaScan@2095a606, KafkaV2[Subscribe[source]], {"source":{"0":11}}, {"source":{"0":11}}

== Physical Plan ==
WriteToDataSourceV2 org.apache.spark.sql.execution.streaming.sources.MicroBatchWrite@6b69d31b, org.apache.spark.sql.execution.datasources.v2.DataSourceV2Strategy$$Lambda$1945/0x000000c001c246c8@28b23a0a
+- *(1) Project [key#7, value#8, topic#9, partition#10, offset#11L, timestamp#12, timestampType#13]
   +- MicroBatchScan[key#7, value#8, topic#9, partition#10, offset#11L, timestamp#12, timestampType#13] class org.apache.spark.sql.kafka010.KafkaSourceProvider$KafkaScan
] with output dataset builders [<function1>, <function1>, <function1>, <function1>, <function1>, <function1>, <function1>, <function1>]

23/09/27 18:17:22 INFO ConsoleTransport: {"eventTime":"2023-09-27T16:17:22.263Z","producer":"https://github.com/OpenLineage/OpenLineage/tree/1.2.2/integration/spark","schemaURL":"https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunEvent","eventType":"COMPLETE","run":{"runId":"3468112f-96c3-44b5-bd84-847c2d99db8f","facets":{"spark_version":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/1.2.2/integration/spark","_schemaURL":"https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunFacet","spark-version":"3.3.0","openlineage-spark-version":"1.2.2"},"processing_engine":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/1.2.2/integration/spark","_schemaURL":"https://openlineage.io/spec/facets/1-1-0/ProcessingEngineRunFacet.json#/$defs/ProcessingEngineRunFacet","version":"3.3.0","name":"spark","openlineageAdapterVersion":"1.2.2"},"environment-properties":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/1.2.2/integration/spark","_schemaURL":"https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunFacet","environment-properties":{}}}},"job":{"namespace":"default","name":"spark_streaming_example.write_to_data_source_v2","facets":{}},"inputs":[],"outputs":[]}
```

As you can see, there are _zero_  inputs and outputs in the corresponding `RunEvent`.

# Stuff to reproduce

## Code

```java
package streaming;

import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.SparkSession;
import org.apache.spark.sql.streaming.StreamingQuery;
import org.apache.spark.sql.streaming.Trigger;

import java.util.concurrent.TimeUnit;

public class SparkStreamingExampleApplication {
    public static void main(String[] args) throws Exception {
        SparkSession spark = SparkSession
                .builder()
                .appName("spark-streaming-example")
                .master("local")
                .config("spark.ui.enabled", false)
                .config("spark.jars.packages", "io.openlineage:openlineage-spark:1.2.2")
                .config("spark.extraListeners", "io.openlineage.spark.agent.OpenLineageSparkListener")
                .config("spark.openlineage.transport.type", "console")
                .config("spark.openlineage.facets.disabled", "[spark_unknown;spark.logicalPlan]")
                .getOrCreate();

        Dataset<Row> df = spark.readStream()
                .format("kafka")
                .option("kafka.bootstrap.servers", "localhost:9092,localhost:9093,localhost:9094")
                .option("subscribe", "source")
                .load();

        StreamingQuery kafkaWriteQuery = df.writeStream()
                .outputMode("append")
                .format("kafka")
                .option("kafka.bootstrap.servers", "localhost:9092,localhost:9093,localhost:9094")
                .option("topic", "target")
                .option("checkpointLocation", "/Users/dhawes/Projects/spark-streaming-openlineage")
                .trigger(Trigger.ProcessingTime(10, TimeUnit.SECONDS))
                .start();

        kafkaWriteQuery.awaitTermination();
    }
}
```

## build.gradle.kts

```gradle
plugins {
    java
    application
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8

    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation("org.apache.spark:spark-core_2.12:3.3.0")
    implementation("org.apache.spark:spark-sql_2.12:3.3.0")
    implementation("org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0")
    implementation("org.apache.spark:spark-streaming_2.12:3.3.0")
    implementation("org.apache.spark:spark-streaming-kafka-0-10_2.12:3.3.0")
    implementation("io.openlineage:openlineage-spark:1.2.2")
}

application {
    mainClass = "streaming.SparkStreamingExampleApplication"
}
```

## docker-compose.yaml

```yaml
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: 'spark-streaming-zookeeper'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka1:
    image: 'confluentinc/cp-kafka:latest'
    container_name: 'spark-streaming-kafka-1'
    depends_on:
      - 'zookeeper'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
    ports:
      - "9092:9094"

  kafka2:
    image: 'confluentinc/cp-kafka:latest'
    container_name: 'spark-streaming-kafka-2'
    depends_on:
      - 'zookeeper'
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9095
    ports:
      - "9093:9095"

  kafka3:
    image: 'confluentinc/cp-kafka:latest'
    container_name: 'spark-streaming-kafka-3'
    depends_on:
      - 'zookeeper'
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9096
    ports:
      - "9094:9096"

  init-kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: 'spark-streaming-kafka-init'
    depends_on:
      - 'kafka1'
      - 'kafka2'
      - 'kafka3'
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka1:9092 --list
      
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka1:9092 --create --if-not-exists --topic source --replication-factor 3 --partitions 1
      kafka-topics --bootstrap-server kafka1:9092 --create --if-not-exists --topic target --replication-factor 3 --partitions 1
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka1:9092 --list
      "
```
