### ISSUE TITLE
OpenLineage configuration inconsistencies

### ISSUE THREAD

**Issue by dolfinus** [OpenLineage/OpenLineage#2555]
For Python Kafka transport config looks like this:
https://openlineage.io/docs/client/python#kafka
```yaml
transport:
  type: kafka
  config:
    bootstrap.servers: mybroker
    acks: all
    retries: 3
  topic: my_topic
  flush: true
```

For Java it looks like this:
https://openlineage.io/docs/client/java/configuration#kafka
```yaml
transport:
  type: kafka
  topicName: openlineage.events
  properties:
    bootstrap.servers: localhost:9092,another.host:9092
    acks: all
    retries: 3
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.apache.kafka.common.serialization.StringSerializer
```

Keys are named differently - `topic` vs. `topicName`, `config` vs. `properties`, no `flush` option in Java config. Is that okay? Is there any plan to synchronise config naming?

For Spark it is also different:
```
spark.openlineage.transport.topicName	Required, name of the topic	topic-name
spark.openlineage.transport.localServerId	Required, id of local server	xxxxxxxx
spark.openlineage.transport.properties.[xxx]	Optional, the [xxx] is property of Kafka client	1
```

What is `localServerId`, why is it required in Spark, but not in Java and Python clients?
