### ISSUE TITLE
Swap Main and Symlink Datasets: Use Glue as Main and S3 as Symlink

### ISSUE THREAD

**Issue by kacpermuda** [OpenLineage/OpenLineage#2718]
**Purpose:**
On running a spark job with AWS Glue assets, OL events are emitted as an S3 dataset instead of Glue. The Glue dataset does come under the symlink facet.

**Proposed implementation**
Instead of relying on the symlink facet, we could support Glue as the main dataset and make S3 (or other underlying source) as a symlink dataset.

**Comment by dolfinus** [comment]
IMHO the same should be done on other synmlinks with TABLE type. For example, creating table in Hive metastore now uses HDFS location as dataset name.

**Comment by pawel-big-lebowski** [comment]
The real problem here is that there's a dataset which can be identified by two identifiers, and only a single identifier is emitted. I don't think changing dataset identifiers' ordering is a valid solution to this problem.

**Comment by dolfinus** [comment]
> and only a single identifier is emitted

Adding both dataset and its symlink to inputs/outputs requires additional deduplication step at events consumer side.
Otherwise this can confuse users, like run has read data from one table and written to another, but lineage has 2 inputs and 2 outputs. Read/write statistics can become duplicated too.

Another thing is that symlinks actually have a direction. Data written to a table is actually stored in location (Hive metastore - symlink -> HDFS path, for my environment). But not all the data written to location is available as table content, e.g. partition information is not yet added to table metadata, or path does not follow partitioning schema, and so on.
Also there can be multiple external tables pointing to the same location, with different set of partitions. So dataset == Hive table with symlink to HDFS location is not the same as having dataset == HDFS location with symlink to Hive table. The latter can be a list of tables, and this mapping could change dynamically.

**Comment by mobuchowski** [comment]
Without discarding the idea: really, I think the problem is in the backend which handles the events. If there are some preferred names (like Glue > S3 location) then the backend can keep some order list and reorder those manually. 

It's not a goal of OL to emit "presentation layer level" data that can, for example be directly displayed on UI without any enrichment or understanding what the OL data is.

>Another thing is that symlinks actually have a direction. Data written to a table is stored in location (Hive metastore - symlink -> HDFS path, for my environment). But not all the data written to location is available as table content, e.g. partition information is not yet added to table metadata, or path does not follow partitioning schema, and so on.

True, that's interesting point. Not sure we give any guarantees tho, like that you can read the data from some dataset, or that some other metadata is available just by knowing the OL metadata related to it.

>Also there can be multiple external tables pointing to the same location, with different set of partitions. So dataset == Hive table with symlink to HDFS location is not the same as having dataset == HDFS location with symlink to Hive table. The latter can be a list of tables, and this mapping could change dynamically.

I disagree that purely the ordering should give some information here. If anything, this could be captured by the additional facet.

>The real problem here is that there's a dataset which can be identified by two identifiers, and only a single identifier is emitted. I don't think changing dataset identifiers' ordering is a valid solution to this problem.

Why do you think there are two distinct datasets there?

**Comment by dolfinus** [comment]
What I'm taking about is that there is a _semantic_ difference between this:
```yml
dataset:
  namespace: hdfs://namenode
  name: /path/to/warehouse/mydb.db/mytable
  facets:
    symlinks:
      - namespace: hive://metastore
        name: mydb.mytable
        type: TABLE
```
and this:
```yml
dataset:
  namespace: hive://metastore
  name: mydb.mytable
  facets:
    symlinks:
      - namespace: hdfs://namenode
        name: /path/to/warehouse/mydb.db/mytable
        type: LOCATION
```

In case of Hive/Glue metastore + HDFS/S3 location second example is more accurate, because of the symlinks are not reversible, and because other reasons I've described above (multiple tables -> one location, no partition info in table metadata ans so on).

I agree that OL backend should have some logic to determine which information is important for a particular case, and which is not. This is not something that should be done on OL client side, as it only have information about current job actions, not overall cluster state.
But emitted event should include symlink information in the first place, to be properly handled later. And currently this information is a bit misleading (in my opinion).

**Comment by dolfinus** [comment]
One question regarding symlinks then no metastore is used.
Currently OL integration for Spark creates dataset like this:
```yaml
dataset:
  namespace: hdfs://namenode
  name: /path/to/warehouse/mydb.db/mytable
  facets:
    symlinks:
      - namespace: hdfs://namenode/path/to/warehouse/mydb.db
        name: mydb.mytable
        type: TABLE
```

Namespace in this case is just path to table's data with stripped table name.

* Should we swap symlink from `TABLE` to `LOCATION` in this case as well?
* Does it make any sense to leave database name in namespace? Warehouse location is actually `hdfs://namenode/path/to/warehouse`.
* For case then table type is a part of its location, like `hdfs://namenode/path/to/warehouse/managed` vs. `hdfs://namenode/path/to/warehouse/external`, should these `managed`/`external` be a part of namespace?
