### ISSUE TITLE
Additional Metadata in Events

### ISSUE THREAD

**Issue by simran-suri** [OpenLineage/OpenLineage#2779]
**Details:**

I am seeking to add more metadata to the OpenLineage events produced by dbt. I can see tags/additional metadata in the manifest.json file of dbt, it is also possible to incorporate this metadata into openlineage events as well.

This is how I'm sending and tagging in dbt.yml:

```
version: 2

sources:
  - name: dbt
    schema: dbt
    database: spark_catalog
    tables:
      - name: customers
        description: "This table contains the final account data"
        columns:
          - name: customer_id
            description: "The unique identifier for the customer"
            meta:
              tags: {"col_id": "customer_id"}
          - name: first_name
            description: "The first name of the customer"
            meta:
              additionalProperties: {"senstive": true}
          - name: last_name
            description: "The last name of the customer"
```

While I can see descriptions for columns and datasets in the events, can we include tags or additionalProperties within the events as well, which could be represented as a key-value pair object.
