### ISSUE TITLE
[FEATURE][SPARK] Change TABLE symlink to point to metastore_db

### ISSUE THREAD

**Issue by dolfinus** [OpenLineage/OpenLineage#2796]
### Motivation

Since #2767, OpenLineage integration for Spark produces following datasets (see discussion https://github.com/OpenLineage/OpenLineage/issues/2718#issuecomment-2152697956):
```yaml
datasets:
  - namespace: hdfs://namenode:8020
    name: /warehouse/with/metastore/database.db/table
    facets:
      symlinks:
        - namespace: hive://metastore:port
          name: database.table
          type: TABLE

  - namespace: hdfs://namenode:8020
    name: /warehouse/without/metastore/database.db/table
    facets:
      symlinks:
        - namespace: hdfs://namehode:8020/warehouse/without/metastore  # no /database.db in the path
          name: database.table
          type: TABLE

  - namespace: hdfs://namenode:8020
    name: /some/custom/location
    # no symlinks for locations not matching warehouse
```

If there is a metastore (case 1), or table is located outside warehouse (case 3) then everything is fine.
But case 2 can be misleading. Symlink is pointing to warehouse, but actual table's metadata is stored not in warehouse, but in metastore.

Note: I'm not talking about for Iceberg, Delta and Hudi formats (warehouse location is fine for those), only [PathUtils.fromCatalog](https://github.com/OpenLineage/OpenLineage/blob/b131895ac2a9b511d5096b152a0ee8335e9398db/integration/spark/shared/src/main/java/io/openlineage/spark/agent/util/PathUtils.java#L41-L89) behavior.

### Description

Probably, in case 2 an internal metastore (Derby) location should be used as symlink namespace, like:
```yaml
datasets:
  - namespace: hdfs://namenode:8020
    name: /warehouse/without/metastore/database.db/table
    facets:
      symlinks:
        - namespace: file:/home/user/spark/metastore_db
          name: database.table
          type: TABLE
```

And if there is no metastore at all (Spark session started without `spark.sql.catalogImplementation=hive`), do not add any symlinks, as table metadata is stored in-memory, and lost after Spark session is stopped.

How Derby database location could be fetched:
```java
class SparkConfUtils {
  private static final String metastoreHadoopJavaxConnectionUrlKey = "javax.jdo.option.ConnectionURL";

  public static Optional<URI> getMetastoreUri(SparkContext context) {
    Optional<String> metastoreUris = findSparkConfigKey(context.getConf(), metastoreUriKey);
    if (!metastoreUris.isPresent()) {
      metastoreUris = findHadoopConfigKey(context.hadoopConfiguration(), metastoreHadoopUriKey);
    }
    if (!metastoreUris.isPresent()) {
      metastoreUris = getDerbyUri(context);
    }
    ...
  }

  private static Optional<URI> getDerbyUri(SparkContext context) {
      //https://github.com/apache/spark/blob/v3.5.1/sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala#L200-L209
      String connectionUrl = findHadoopConfigKey(contextHadoopConfiguration, metastoreHadoopJavaxConnectionUrlKey)
        .filter(uri -> !uri.startsWith("jdbc:derby:in-memory"));
      if (!connectionUrl.isPresent()) return Optional.empty();

      // extract 'metastore_db' from 'jdbc:derby:;databaseName=metastore_db;others'
      String databaseName = ...;

      // get Derby location, e.g. /tmp or /current/dir
      // https://db.apache.org/derby/docs/10.3/tuning/rtunproper32066.html
      String derbyHome = Optional.of(System.getProperty("derby.system.home")).orElse(System.getProperty("user.dir"));
      return Optional.of(derbyHome + File.separator + databaseName);
  }
}
```

### Related issues

2718

### Do you plan to make this contribution yourself?

- [X] I am interested in doing this work
