### ISSUE TITLE
[FEATURE] Allow overriding dataset namespace for DBT

### ISSUE THREAD

**Issue by dolfinus** [OpenLineage/OpenLineage#3714]
### Motivation

For now, dbt-spark integration produces datasets with namespace like `spark://thrift-host:thrift-port`. This is because OpenLineage requires some namespace for dataset, and the only data DBT have for Spark its address.

But Spark tables are actually stored in some filesystem (S3, HDFS, local), with metadata stored in some metastore (local, Hive, Iceberg and so on). This leads to producing different dataset namespaces in OpenLineage events produced by Spark integration (`s3://bucket/path` + SYMLINK `hive://metastore:20000`) and produced by DBT (`spark://localhost:10000`).

### Description

Introduce namespace overriding option to OpenLineage config:
```yaml
openlineage:
  dataset:
    namespace: hive://metastore:20000
```

If namespace is set, integrations like DBT will prefer using it for building OpenLineage events. Default value is `null`, which means use current mechanism of generating namespace.

### Do you plan to make this contribution yourself?

- [x] I am interested in doing this work

**Comment by dolfinus** [comment]
There is `openlineage.dataset.namespaceResolvers` which can modify dataset namespace based on some rules defined by user. But these modify only URL `authority` component, and keep original schema intact.

**Comment by mobuchowski** [comment]
Would it not be better to fix `openlineage.dataset.namespaceResolvers`? I think the static replace has the problem of being vulnerable to changes, while you can take it into account in the rules.

**Comment by dolfinus** [comment]
This could bring unnecessary complexity to resolvers mechanism

**Comment by dolfinus** [comment]
Maybe something like this could work:
```yml
dataset:
  namespaceResolvers:
    hive://localhost:10000:
      type: pattern
      schema: spark
      regex: localhost:20000
```

If resolved name includes schema and port, they are overriding original ones.

Also for now resolvers implemented only for Java client, not Python. But this will be easy to implement.

**Comment by kacpermuda** [comment]
I'd also prefer non-static solution, something like the above, if you use explicitly specify some config and then if the dataset namespace / name match some predefined condition (regex, exact etc.) it can be replaces with a new one (either static or some dynamic function that accepts old and returns new).

**Comment by amrnablus** [comment]
That would require the settings to change if the namespace resolvers change in the future, as well as if the data source changed, think of this:
i'm testing on my local environment, my resolved namespace would be "psotgres://localhost:5432" i use that as my regex, all is good.

Now i go to production, my postgres namespace would be "postgres://postgres.example.com" which will not match the pattern and will cause production issues...

**Comment by amrnablus** [comment]
A better approach would be allowing overriding the namcespace on a data source level, something like:
```
dataset:
  namespaceResolvers:
    postgres:
      type: source
      schema: spark
      namespace: "example-postgres"
```

this way, any data coming from any postgres source will go to the example namespace.
