### ISSUE TITLE
[BUG] openlineage-flink logs "JobId is not set" for certain StatusEvents in FlinkSQL

### ISSUE THREAD

**Issue by fetta** [OpenLineage/OpenLineage#3788]
### OpenLineage integration/client

Flink integration

### OpenLineage version

openlineage-flink 1.33.0

### Technology and package versions

Flink 2.0 (official docker)
openlineage-flink 1.33.0
Kafka 4.0 the lineage publishes to
all relevant library versions in the Environment configuration section

### Environment configuration

Flink 2.0 using docker-compose:

flink services:
```

  flink-jobmanager:
    image: flink:2.0.0
    depends_on:
      - kafka
      - schema-registry
    expose:
      - "6123"
    ports:
      - "8082:8081" # conflict with schema-registry on 8081
      - "8083:8083"
    command: |
      bash -c "  
      /opt/flink/bin/jobmanager.sh start-foreground &
      /opt/flink/bin/sql-gateway.sh start-foreground
      "
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
      OPENLINEAGE_CONFIG: /opt/flink/conf/openlineage.yml
      FLINK_PROPERTIES: |
        execution.job-status-changed-listeners: io.openlineage.flink.listener.OpenLineageJobStatusChangedListenerFactory
        sql-gateway.endpoint.rest.address: 0.0.0.0  
        sql-gateway.endpoint.rest.port: 8083
    volumes:
      #      - ./resources/flink-openlineage.http.yaml:/opt/flink/conf/openlineage.yml
      - ./resources/flink-openlineage.kafka.yaml:/opt/flink/conf/openlineage.yml
      - ./flink-jars/flink-sql-connector-kafka-4.0.0-2.0.jar:/opt/flink/lib/flink-sql-connector-kafka-4.0.0-2.0.jar
      - ./flink-jars/flink-avro-2.0.0.jar:/opt/flink/lib/flink-avro-2.0.0.jar
      - ./flink-jars/flink-avro-confluent-registry-2.0.0.jar:/opt/flink/lib/flink-avro-confluent-registry-2.0.0.jar
      - ./flink-jars/openlineage-flink-1.33.0.jar:/opt/flink/lib/openlineage-flink-1.33.0.jar
      - ./flink-jars/avro-1.12.0.jar:/opt/flink/lib/avro-1.12.0.jar
      - ./flink-jars/flink-sql-avro-confluent-registry-2.0.0.jar:/opt/flink/lib/flink-sql-avro-confluent-registry-2.0.0.jar
      - ./flink-jars/kafka-schema-registry-client-7.9.1.jar:/opt/flink/lib/kafka-schema-registry-client-7.9.1.jar
      - ./flink-jars/kafka-avro-serializer-7.9.1.jar:/opt/flink/lib/kafka-avro-serializer-7.9.1.jar
      - ./flink-jars/kafka-clients-4.0.0.jar:/opt/flink/lib/kafka-clients-4.0.0.jar
      - ./resources/flink-sql-job.sql:/opt/flink/sql-job.sql
    networks:
      - app_net
  flink-taskmanager:
    image: flink:2.0.0
    expose:
      - "6121"
      - "6122"
    depends_on:
      - flink-jobmanager
    command: taskmanager
    links:
      - "flink-jobmanager:flink-jobmanager"
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
      OPENLINEAGE_CONFIG: /opt/flink/conf/openlineage.yml
      FLINK_PROPERTIES: |
        execution.job-status-changed-listeners: io.openlineage.flink.listener.OpenLineageJobStatusChangedListenerFactory
    volumes:
#      - ./resources/flink-openlineage.http.yaml:/opt/flink/conf/openlineage.yml
      - ./resources/flink-openlineage.kafka.yaml:/opt/flink/conf/openlineage.yml
      - ./flink-jars/flink-sql-connector-kafka-4.0.0-2.0.jar:/opt/flink/lib/flink-sql-connector-kafka-4.0.0-2.0.jar
      - ./flink-jars/flink-avro-2.0.0.jar:/opt/flink/lib/flink-avro-2.0.0.jar
      - ./flink-jars/flink-avro-confluent-registry-2.0.0.jar:/opt/flink/lib/flink-avro-confluent-registry-2.0.0.jar
      - ./flink-jars/openlineage-flink-1.33.0.jar:/opt/flink/lib/openlineage-flink-1.33.0.jar
      - ./flink-jars/avro-1.12.0.jar:/opt/flink/lib/avro-1.12.0.jar
      - ./flink-jars/flink-sql-avro-confluent-registry-2.0.0.jar:/opt/flink/lib/flink-sql-avro-confluent-registry-2.0.0.jar
      - ./flink-jars/kafka-schema-registry-client-7.9.1.jar:/opt/flink/lib/kafka-schema-registry-client-7.9.1.jar
      - ./flink-jars/kafka-avro-serializer-7.9.1.jar:/opt/flink/lib/kafka-avro-serializer-7.9.1.jar
      - ./flink-jars/kafka-clients-4.0.0.jar:/opt/flink/lib/kafka-clients-4.0.0.jar

```

flink-openlineage.kafka.yaml:
```
transport:
  type: kafka
  topicName: flink-openlineage-events
  properties:
    bootstrap.servers: kafka:9094
    acks: all
    retries: 3
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.apache.kafka.common.serialization.StringSerializer
job:
  namespace: flink-jobs
namespace: flink.prod.v1 # For the OpenLineage producer itself
dataset:
  kafka:
    resolveTopicPattern: true
  namespaceResolvers:
    kafka-prod:
      type: hostList
      hosts: ['kafka:9094']
      schema: kafka
trackingIntervalInSeconds: 15

```

FlinkSQL:

```
SET
'pipeline.name' = 'basic-flink-sql-job';
    -- =============================================================================
    --  Source Table from Kafka
    -- =============================================================================
CREATE TABLE source_topic
(
    `text` STRING
) WITH (
      'connector' = 'kafka',
      'topic' = 'lineage-test-topic-forflink',
      'properties.bootstrap.servers' = 'kafka:9094',
      'properties.group.id' = 'flink-lineage-test-group',
      'scan.startup.mode' = 'latest-offset',
      'format' = 'avro-confluent',
      'avro-confluent.url' = 'http://schema-registry:8081'
      );

-- =============================================================================
--  Sink Table to Kafka
-- =============================================================================

CREATE TABLE sink_topic
(
    `text` STRING
) WITH (
      'connector' = 'kafka',
      'topic' = 'lineage-test-topic-forflink-output',
      'properties.bootstrap.servers' = 'kafka:9094',
      'format' = 'avro-confluent',
      'avro-confluent.url' = 'http://schema-registry:8081'
      );

-- =============================================================================
--  The Streaming Job 🚀
--  Appends ' - processed by Flink' to the 'text' field.
-- =============================================================================
INSERT INTO sink_topic
SELECT `text` || ' - processed by Flink'
FROM source_topic;

```

kafka services (not directly relevant but hopefully helpful:

```

  kafka:
    image: docker.io/bitnami/kafka:4.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CLUSTER_ID=lkorDA4qT6W1K_dk0LHvtg
      # Start Kraft Setup (Kafka as Controller - no Zookeeper)
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIRS=/tmp/logs
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094
      # End Kraft Specific Setup
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,INTERNAL://kafka:9094
    healthcheck:
      interval: 1s
      retries: 5
      start_period: 60s
      test: [ "CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092" ]
      timeout: 5s
    volumes:
      - "kafka-data:/bitnami"
    networks:
      - app_net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local-docker-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - app_net
  schema-registry:
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schemaregistry
      - SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=PLAINTEXT
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:9094
    healthcheck:
      interval: 1s
      retries: 3
      start_period: 60s
      test: nc -z schema-registry ${DATAHUB_SCHEMA_REGISTRY_PORT:-8081}
      timeout: 5s
    hostname: schema-registry
    image: ${DATAHUB_CONFLUENT_SCHEMA_REGISTRY_IMAGE:-confluentinc/cp-schema-registry}:${DATAHUB_CONFLUENT_VERSION:-7.9.1}
    ports:
      - ${DATAHUB_MAPPED_SCHEMA_REGISTRY_PORT:-8081}:8081
    networks:
      - app_net
```

I also have some java code that publishes to the topics my flink sql is consuming from.

### Deployment details

only local docker compose

### Problem details

openlineage-flink library doesn't have access to JobId, even though Flink logs that happen right before have access to JobId. I suspect that because of this not all events that should be emitted are emitted.

### What you think should happen instead

Some events are not emitted because of this according to logs. Should be emitted, and WARN shouldn't be there.

### How to reproduce

1. run the containers
2. run the flink sql (you might need to create the topics beforehand, I'm not sure)
3. Publish something to `lineage-test-topic-forflink`. The schema is { "text": STRING }
4. Check the logs of jobmanager for the entry

` WARN  io.openlineage.flink.listener.OpenLineageJobStatusChangedListener [] - JobId is not set, skipping event: org.apache.flink.core.execution.DefaultJobExecutionStatusEvent@227f8ef7`. You can also check the topic `flink-openlineage-events` to see what actually gets published.

### Do you plan to make this contribution yourself?

- [x] I am interested in doing this work
